export const projectForm = [
    {
      label: "Empresa",
      name: "empresa",
      type: "text",
      className: "modalInput",
      placeholder: "Empresa",
      required: true,
      object: "input",
    },
    {
      label: "Retorno Interes",
      name: "retornoInteres",
      type: "text",
      className: "modalInput modalSelect",
      placeholder: "",
      required: true,
      object: "select",
    },
    {
      label: "Retorno Capital",
      name: "retornoCapital",
      type: "text",
      className: "modalInput modalSelect",
      placeholder: "",
      required: true,
      object: "select",
    },
    {
      label: "Tasa Anual",
      name: "t_anual",
      type: "text",
      className: "modalInput",
      placeholder: "Tasa Anual",
      required: true,
      object: "input",
    },
    {
      label: "Periodo",
      name: "periodo",
      type: "text",
      className: "modalInput",
      placeholder: "Periodo",
      required: true,
      object: "input",
    },
  ];